FORMAT: 1A
HOST: http://127.0.0.1:3000/

# ArtGear

ArtGear - Graphics Task Manager

<!-- TOKEN START -->

## Login [/login]

### Login [POST]

+ Request (application/json)
    + Headers
    
            Accept: application/json
            
    + Body
    
            {
                "login": "MatejkoPL",
                "password": "Stanczyk123!"
            }


+ Response 200 (application/json)

        {
            "token": "kQqci2KbktyAetKd12J4TCFa" 
        }
        
+ Response 401 (application/json)

        {
            "error": "Incorrect credentials"
        }

<!-- TOKEN END -->

<!-- ARTISTS START -->

## All Artists [/artists]

### List All Artists [GET]

+ Request
    + Headers
    
            Accept: application/json

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "login": "MatejkoPL",
                "password_digest": "90a3cea11ea9b3be14efe8bb9f3ad647",
                "nickname": "Matejko",
                "bio": "Painter...",
                "preferred_style": "Old painting"
            }
        ]
        
+ Response 500 (application/json)

        {
            "error": "Internal Server Error"
        }

### Create An Artist [POST]

+ Request (application/json)
    + Headers
    
            Accept: application/json
            
    + Body
    
            {
                "login": "MatejkoPL",
                "password": "Stanczyk123!",
                "nickname": "Matejko",
                "bio": "Painter...",
                "preferred_style": "Old painting"
            }

+ Response 201 (application/json)

        {
                "id": 1,
                "login": "MatejkoPL",
                "password_digest": "90a3cea11ea9b3be14efe8bb9f3ad647",
                "nickname": "Matejko",
                "bio": "Painter...",
                "preferred_style": "Old painting"
        }
        
+ Response 422 (application/json)

        {
            "error": "Unprocessable Entity"
        }
        
## An Artist [/artists/{id}]

### List An Artist [GET]

+ Request
    + Headers
        
            Accept: application/json
        
+ Parameters
    + id: 1 (integer) - ID of an artist
    
+ Response 200 (application/json)

        {
                "id": 1,
                "login": "MatejkoPL",
                "password_digest": "90a3cea11ea9b3be14efe8bb9f3ad647",
                "nickname": "Matejko",
                "bio": "Painter...",
                "preferred_style": "Old painting"
        }
        
+ Response 404 (application/json)

        {
            "error": "Couldn't find Artist with 'id'=1"
        }
        
### Delete An Artist [DELETE]

+ Request
    + Headers
        
            Accept: application/json
            Authorization: [auth_token]
        
+ Parameters
    + id: 1 (integer) - ID of an artist
    
+ Response 200 (application/json)

        {
            "success": "true"
        }
        
+ Response 404 (application/json)

        {
            "error": "Couldn't find Artist with 'id'=1"
        }
        
### Update An Artist [PATCH]

+ Request (application/json)
    + Headers
    
            Accept: application/json
            Authorization: [auth_token]
            
    + Body
    
            {
                "password": "Stanczyk123!",
                "nickname": "Matejko",
                "bio": "Painter...",
                "preferred_style": "Old painting"
            }
            
    
+ Parameters
    + id: 1 (integer) - ID of an artist

+ Response 200 (application/json)

        {
                "id": 1,
                "login": "MatejkoPL",
                "password_digest": "90a3cea11ea9b3be14efe8bb9f3ad647",
                "nickname": "Matejko",
                "bio": "Painter...",
                "preferred_style": "Old painting"
        }
        
+ Response 404 (application/json)

        {
            "error": "Couldn't find Artist with 'id'=1"
        }

+ Response 422 (application/json)

        {
            "error": "Unprocessable Entity"
        }
        
## Artist's Orders [/artists/{id}/orders]

### List Artist's Orders [GET]

+ Request
    + Headers
    
            Accept: application/json
            Authorization: [auth_token]
            
+ Parameters
    + id: 1 (integer) - ID of an artist

+ Response 200 (application/json)

        {
            "id": 1,
            "login": "MatejkoPL",
            "orders": [
                {
                    "id": 1,
                    "order_status": "CREATED",
                    "notes": "Logo with pink ponies",
                    "client": {
                        "id": 1,
                        "full_name": "Jan Kowalski",
                        "email": "jan.kowalski@gmail.com",
                        "phone": "587458625",
                        "age": 18
                    },
                    "service": {
                        "id": 1,
                        "name": "Making a logo",
                        "category": {
                            "id": 1,
                            "name": "Logo"
                        }
                    }
                }
            ]
        }
        
+ Response 404 (application/json)

        {
            "error": "Couldn't find Artist with 'id'=1"
        }

<!-- ARTIST END -->

<!-- CLIENTS START -->

## All Clients [/clients]

### List All Clients [GET]

+ Request
    + Headers
    
            Accept: application/json

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "full_name": "Jan Kowalski",
                "email": "jan.kowalski@gmail.com",
                "phone": "587458625",
                "age": 18
            }
        ]

+ Response 500 (application/json)

        {
            "error": "Internal Server Error"
        }

### Create A Client [POST]

+ Request (application/json)
    + Headers
    
            Accept: application/json
            Authorization: [auth_token]
            
    + Body
    
            {
                "full_name": "Jan Kowalski",
                "email": "jan.kowalski@gmail.com",
                "phone": "587458625",
                "age": "18"
            }

+ Response 201 (application/json)

        {
            "id": 1,
            "full_name": "Jan Kowalski",
            "email": "jan.kowalski@gmail.com",
            "phone": "587458625",
            "age": 18
        }
        
+ Response 422 (application/json)

        {
            "error": "Unprocessable Entity"
        }

## A Client [/clients/{id}]

### List A Client [GET]

+ Request
    + Headers
        
            Accept: application/json
        
+ Parameters
    + id: 1 (integer) - ID of a client
    
+ Response 200 (application/json)

        {
            "id": 1,
            "full_name": "Jan Kowalski",
            "email": "jan.kowalski@gmail.com",
            "phone": "587458625",
            "age": 18
        }
        
+ Response 404 (application/json)

        {
            "error": "Couldn't find Client with 'id'=1"
        }
        
### Delete A Client [DELETE]

+ Request
    + Headers
        
            Accept: application/json
            Authorization: [auth_token]
        
+ Parameters
    + id: 1 (integer) - ID of a client
    
+ Response 200 (application/json)

        {
            "success": "true"
        }
        
+ Response 404 (application/json)

        {
            "error": "Couldn't find Client with 'id'=1"
        }
        
### Update A Client [PATCH]

+ Request (application/json)
    + Headers
    
            Accept: application/json
            Authorization: [auth_token]
            
    + Body
    
            {
                "full_name": "Piotr Nowak",
                "email": "piotr.nowak@gmail.com",
                "phone": "698741258",
                "age": 45
            }
    
+ Parameters
    + id: 1 (integer) - ID of a client

+ Response 200 (application/json)

        {
            "id": 1,
            "full_name": "Piotr Nowak",
            "email": "piotr.nowak@gmail.com",
            "phone": "698741258",
            "age": 45
        }
        
+ Response 404 (application/json)

        {
            "error": "Couldn't find Client with 'id'=1"
        }

+ Response 422 (application/json)

        {
            "error": "Unprocessable Entity"
        }
        
## User's Orders [/clients/{id}/orders]

### List Client's Orders [GET]

+ Request
    + Headers
    
            Accept: application/json
            
+ Parameters
    + id: 1 (integer) - ID of a client

+ Response 200 (application/json)

        {
            "id": 1,
            "full_name": "Jan Kowalski",
            "orders": [
                {
                    "id": 1,
                    "order_status": "CREATED",
                    "notes": "Logo with pink ponies",
                    "artist": {
                        "id": 1,
                        "nickname": "Matejko",
                        "bio": "Painter...",
                        "preferred_style": "Old painting"
                    },
                    "service": {
                        "id": 1,
                        "name": "Making a logo",
                        "category": {
                            "id": 1,
                            "name": "Logo"
                        }
                    }
                }
            ]
        }
        
+ Response 404 (application/json)

        {
            "error": "Couldn't find Client with 'id'=1"
        }
        
<!-- CLIENTS END -->

<!-- ADDRESSES START -->

## All Addresses [/clients/{id}/addresses]

### List Addresses [GET]

+ Request
    + Headers
    
            Accept: application/json
            
+ Parameters
  + id: 1 (integer) - ID of a client

+ Response 200 (application/json)

        
            [
                {
                    "id": 1,
                    "address_line_1": "Plac Grunwaldzki",
                    "address_line_2": "109",
                    "postal_code": "50379",
                    "city": "Wrocław",
                    "country": "PL"
                }
            ]
            
+ Response 404 (application/json)

        {
            "error": "Couldn't find Client with 'id'=1"
        }
        
### Create An Address [POST]

+ Request (application/json)
    + Headers
    
            Accept: application/json
            Authorization: [auth_token]
            
    + Body
    
            {
                "address_line_1": "Plac Grunwaldzki",
                "address_line_2": "109",
                "postal_code": "50379",
                "city": "Wrocław",
                "country": "PL"
            }
            
+ Parameters
  + id: 1 (integer) - ID of a client

+ Response 201 (application/json)

        
            {
                "id": 1,
                "address_line_1": "Plac Grunwaldzki",
                "address_line_2": "109",
                "postal_code": "50379",
                "city": "Wrocław",
                "country": "PL",
                "client":
                {
                    "id": 1,
                    "full_name": "Jan Kowalski",
                    "email": "jan.kowalski@gmail.com" ,
                    "phone": "587458625",
                    "age" : 18
                }
            }
        
        
+ Response 422 (application/json)

        {
            "error": "Unprocessable Entity"
        }
        
## An Address [/clients/{id}/addresses/{address_id}]
### Delete An Address [DELETE]

+ Request
    + Headers
    
            Accept: application/json
            Authorization: [auth_token]
        
+ Parameters
    + address_id: 1 (integer) - ID of an address
    + id: 1 (integer) - ID of a client
    
+ Response 200 (application/json)

        {
            "success": "true"
        }
        
+ Response 404 (application/json)

        {
            "error": "Couldn't find Address with 'id'=1"
        }
        
### Update An Address [PATCH]

+ Request (application/json)
    + Headers
    
            Accept: application/json
            Authorization: [auth_token]
            
    + Body
    
            {
                "address_line_1": "Kosciuszki",
                "address_line_2": "109",
                "postal_code": "50370",
                "city": "Wrocław",
                "country": "PL"
            }
    
+ Parameters
    + address_id: 1 (integer) - ID of an address
    + id: 1 (integer) - ID of a client

+ Response 200 (application/json)

            {
                "id": 1,
                "address_line_1": "Kosciuszki",
                "address_line_2": "109",
                "postal_code": "50370",
                "city": "Wrocław",
                "country": "PL",
                "client":
                {
                    "id": 1,
                    "full_name": "Jan Kowalski",
                    "email": "jan.kowalski@gmail.com" ,
                    "phone": "587458625",
                    "age" : 18
                }
            }
            
+ Response 404 (application/json)

        {
            "error": "Couldn't find Address with 'id'=1"
        }

+ Response 422 (application/json)

        {
            "error": "Unprocessable Entity"
        }

<!-- ADDRESSES END -->

<!-- SERVICES START -->

## All Services [/services]

### List All Services [GET]

+ Request
    + Headers
    
            Accept: application/json

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Making a logo",
                "category:":
                {
                    "id": 1,
                    "name": "Logo"
                }
            }
        ]
        
+ Response 500 (application/json)

        {
            "error": "Internal Server Error"
        }

### Create A Service [POST]

+ Request (application/json)
    + Headers
    
            Accept: application/json
            Authorization: [auth_token]
            
    + Body
    
            {
                "name": "Making a logo",
                "category_id": 1
            }

+ Response 201 (application/json)

        {
            "id": 1,
            "name": "Making a logo",
            "category:":
            {
                "id": 1,
                "name": "Logo"
            }
        }

+ Response 422 (application/json)

        {
            "error": "Unprocessable Entity"
        }

## A Service [/services/{id}]

### List A Service [GET]

+ Request
    + Headers
    
            Accept: application/json
        
+ Parameters
    + id: 1 (integer) - ID of a service
    
+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Making a logo",
            "category:":
            {
                "id": 1,
                "name": "Logo"
            }
        }
        
+ Response 404 (application/json)

        {
            "error": "Couldn't find Service with 'id'=1"
        }
        
### Delete A Service [DELETE]

+ Request
    + Headers
    
            Accept: application/json
            Authorization: [auth_token]
        
+ Parameters
    + id: 1 (integer) - ID of a service
    
+ Response 200 (application/json)

        {
            "success": "true"
        }
        
+ Response 404 (application/json)

        {
            "error": "Couldn't find Service with 'id'=1"
        }
        
### Update A Service [PATCH]

+ Request (application/json)
    + Headers
    
            Accept: application/json
            Authorization: [auth_token]
            
    + Body
    
            {
                "name": "Making a poster",
                "category_id": 2
            }
    
+ Parameters
    + id: 1 (integer) -  ID of a service

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Making a poster",
            "category:":
            {
                "id": 2,
                "name": "Poster"
            }
        }
        
+ Response 404 (application/json)

        {
            "error": "Couldn't find Service with 'id'=1"
        }

+ Response 422 (application/json)

        {
            "error": "Unprocessable Entity"
        }
        
<!-- SERVICES END -->

<!-- CATEGORIES START -->

## All Categories [/categories]

### List All Categories [GET]

+ Request
    + Headers
    
            Accept: application/json

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Logo"
            }
        ]
        
+ Response 500 (application/json)

        {
            "error": "Internal Server Error"
        }

### Create A Category [POST]

+ Request (application/json)
    + Headers
    
            Accept: application/json
            Authorization: [auth_token]
            
    + Body
    
            {
                "name": "Logo",
            }

+ Response 201 (application/json)

        {
            "id": 1,
            "name": "Logo"
        }

+ Response 422 (application/json)

        {
            "error": "Unprocessable Entity"
        }

## A Category [/categories/{id}]

### List A Category [GET]

+ Request
    + Headers
    
            Accept: application/json
        
+ Parameters
    + id: 1 (integer) - ID of a category
    
+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Logo"
        }
        
+ Response 404 (application/json)

        {
            "error": "Couldn't find Category with 'id'=1"
        }
        
### Delete A Category [DELETE]

+ Request
    + Headers
    
            Accept: application/json
            Authorization: [auth_token]
        
+ Parameters
    + id: 1 (integer) - ID of a category
    
+ Response 200 (application/json)

        {
            "success": "true"
        }
        
+ Response 404 (application/json)

        {
            "error": "Couldn't find Category with 'id'=1"
        }
        
### Update A Category [PATCH]

+ Request (application/json)
    + Headers
    
            Accept: application/json
            Authorization: [auth_token]
            
    + Body
    
            {
                "name": "Poster",
            }
    
+ Parameters
    + id: 1 (integer) - ID of a category

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Poster"
        }
        
+ Response 404 (application/json)

        {
            "error": "Couldn't find Category with 'id'=1"
        }

+ Response 422 (application/json)

        {
            "error": "Unprocessable Entity"
        }
        
## Services By Category [/categories/{id}/services]

### List Services by Category [GET]

+ Request
    + Headers
    
            Accept: application/json
        
+ Parameters
    + id: 1 (integer) - ID of a service category
    
+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Logo",
            "services": [
                {
                    "id": 1,
                    "name": "Making a logo"
                }
            ]
        }
        
+ Response 404 (application/json)

        {
            "error": "Couldn't find Category with 'id'=1"
        }
        
<!-- CATEGORIES END -->

<!-- ORDERS START -->

## All Orders [/orders]

### List All Orders [GET]

+ Request
    + Headers
    
            Accept: application/json

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "client":
                {
                    "id": 1,
                    "full_name": "Jan Kowalski",
                    "email": "jan.kowalski@gmail.com" ,
                    "phone": "587458625",
                    "age" : 18
                },
                "artist":
                {
                    "id": 1,
                    "nickname":"Matejko",
                    "bio:":"Painter… ",
                    "preferred_style": "Old paintings"
                },
                "service":
                {
                    "id": 1,
                    "name":"Making a logo",
                    "category:":
                    {
                        "id": 1,
                        "name": "Logo"
                    }
                },
                "order_status": "CREATED",
                "notes": "Contact via email"
            }
        ]
        
+ Response 500 (application/json)

        {
            "error": "Internal Server Error"
        }

### Create An Order [POST]

+ Request (application/json)
    + Headers
    
            Accept: application/json
            
    + Body
    
            {
                "client_id": 1,
                "artist_id": 1,
                "service_id": 1,
                "notes": "Contact via email",
            }

+ Response 201 (application/json)

            {
                "id": 1,
                "client":
                {
                    "id": 1,
                    "full_name": "Jan Kowalski",
                    "email": "jan.kowalski@gmail.com" ,
                    "phone": "587458625",
                    "age" : 18
                },
                "artist":
                {
                    "id": 1,
                    "nickname":"Matejko",
                    "bio:":"Painter… ",
                    "preferred_style": "Old paintings"
                },
                "service":
                {
                    "id": 1,
                    "name":"Making a logo",
                    "category:":
                    {
                        "id": 1,
                        "name": "Logo"
                    }
                },
                "order_status": "CREATED",
                "notes": "Contact via email"
            }
            
+ Response 422 (application/json)

        {
            "error": "Unprocessable Entity"
        }

## An Order [/orders/{id}]

### List An Order [GET]

+ Request
    + Headers
    
            Accept: application/json
        
+ Parameters
    + id: 1 (integer) - ID of an order
    
+ Response 200 (application/json)

            {
                "id": 1,
                "client":
                {
                    "id": 1,
                    "full_name": "Jan Kowalski",
                    "email": "jan.kowalski@gmail.com" ,
                    "phone": "587458625",
                    "age" : 18
                },
                "artist":
                {
                    "id": 1,
                    "nickname":"Matejko",
                    "bio:":"Painter… ",
                    "preferred_style": "Old paintings"
                },
                "service":
                {
                    "id": 1,
                    "name":"Making a logo",
                    "category:":
                    {
                        "id": 1,
                        "name": "Logo"
                    }
                },
                "order_status": "IN_PROGRESS",
                "notes": "Contact via email"
            }
            
+ Response 404 (application/json)

        {
            "error": "Couldn't find Order with 'id'=1"
        }
        
### Delete An Order [DELETE]

+ Request
    + Headers
    
            Accept: application/json
        
+ Parameters
    + id: 1 (integer) - ID of an order
    
+ Response 200 (application/json)

        {
            "success": "true"
        }
        
+ Response 404 (application/json)

        {
            "error": "Couldn't find Order with 'id'=1"
        }
        
### Update An Order Status [PATCH]

+ Request (application/json)
    + Headers
    
            Accept: application/json
            Authorization: [auth_token]
            
    + Body
    
            {
                "order_status": "COMPLETED"
            }
            
+ Parameters
    + id: 1 (integer) - ID of an order

+ Response 200 (application/json)

            {
                "id": 1,
                "client":
                {
                    "id": 1,
                    "full_name": "Jan Kowalski",
                    "email": "jan.kowalski@gmail.com" ,
                    "phone": "587458625",
                    "age" : 18
                },
                "artist":
                {
                    "id": 1,
                    "nickname":"Matejko",
                    "bio:":"Painter… ",
                    "preferred_style": "Old paintings"
                },
                "service":
                {
                    "id": 1,
                    "name":"Matejko",
                    "category:":
                    {
                        "id": 1,
                        "name": "Logo"
                    }
                },
                "order_status": "COMPLETED",
                "notes": "Contact via email"
            }
            
+ Response 404 (application/json)

        {
            "error": "Couldn't find Order with 'id'=1"
        }

+ Response 422 (application/json)

        {
            "error": "Unprocessable Entity"
        }

<!-- ORDERS END -->